trainingInput:
  scaleTier: STANDARD_1
  hyperparameters:
    goal: MINIMIZE
    hyperparameterMetricTag: rmse 
    enableTrialEarlyStopping: True
    maxTrials: 200
    maxParallelTrials: 4
    params:
    - parameterName: learning_rate
      type: DISCRETE
      discreteValues:
      - 0.000001
      - 0.00001
      - 0.001
    - parameterName: first_layer_size
      type: INTEGER
      minValue: 100
      maxValue: 300
      scaleType: UNIT_LOG_SCALE
    - parameterName: layer_reduction_fraction
      type: DOUBLE
      minValue: 0.1
      maxValue: 1
      scaleType: UNIT_LINEAR_SCALE
    - parameterName: number_layers
      type: INTEGER
      minValue: 1
      maxValue: 5
      scaleType: UNIT_LOG_SCALE
    - parameterName: batch_size
      type: DISCRETE
      discreteValues:
      - 32
      - 64
      - 128
